### ISSUE TITLE
Google Cloud Deployment error

### ISSUE THREAD

**Issue by allamedo** [ryderdamen/Google-Cloud-Functions-PhantomJS-Scraper#2]
Hello @ryderdamen,

First of all thank you for making this repository public.

I'm trying to deploy it on my Google Cloud project but I'm getting this error:

`$ make deploy
Enter GCloud Project Name: XXXX
Enter Function Name: phantomJS-scraper
WARNING: The nodejs8 runtime is deprecated on Cloud Functions. Please migrate to a newer Node.js version (--runtime=nodejs12). See https://cloud.google.com/functions/docs/migrating/nodejs-runtimes
Allow unauthenticated invocations of new function [phantomJS-scraper]? (y/N)?  y

Deploying function (may take a while - up to 2 minutes)...working.
For Cloud Build Logs, visit: https://console.cloud.google.com/cloud-build/builds;region=us-central1/6858bb14-3e95-44c1-99ea-40a0246de4e4?project=XXXXXXXX
Deploying function (may take a while - up to 2 minutes)...failed.   
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: > phantom_scraper@1.0.0 preinstall /workspace
> apt-get update && apt-get -y install libfontconfig1

Reading package lists...
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! phantom_scraper@1.0.0 preinstall: `apt-get update && apt-get -y install libfontconfig1`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the phantom_scraper@1.0.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /www-data-home/.npm/_logs/2022-01-12T10_17_29_173Z-debug.log; Error ID: b0ba1f57
make: *** [Makefile:7: deploy] Error 1`

I have no experience with NodeJS so maybe you could take a look?
Thanks!

**Comment by ryderdamen** [comment]
Hey @allamedo,

I'm going to archive this repository - it's pretty old.

When I originally built it, GCP allowed you to do an apt-get install command as a part of the pre-install script for npm install, but as I remember at the time it was a bit of a hack - and after doing a bit of checking it seems it is now no longer possible.

https://stackoverflow.com/questions/52012433/google-cloud-functions-gcf-installing-packages-with-apt-get

In general, now that Google Cloud Run is available, I'd recommend using it, with a PhantomJS or Selenium containing docker container, wrapped with a simple API like this repository implemented, to handle your scraping. Cloud Run does also scale to zero, so it's relatively affordable too.

Sorry about the trouble - best of luck!
